language: node_js
node_js:
- 6.2.2
sudo: false
before_install:
- chmod 755 ./deploy.sh
- chmod 755 ./copy-files.sh
install: npm --production=false install
script: npm run build
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true